### ISSUE TITLE
Migrate SharedDataPtr to std::shared_ptr

### ISSUE THREAD

**Issue by rodrigosetti** [nucleic/kiwi#107]
Apologies if I missed why this isn't possible or wanted.

Looks like [SharedDataPtr](../blob/main/kiwi/shareddata.h) replicates the functionality of [std::shared_ptr](https://en.cppreference.com/w/cpp/memory/shared_ptr).

`std::shared_ptr` performance is very good. Using it would make the code more readable (because it's standard), and it would remove the need to maintain `SharedDataPtr`. Does it make sense to migrate?

**Comment by MatthieuDartiailh** [comment]
It would. The codebase needed at first to support old msvc versions (due to Python 2 support) on which the std implementation was not available. And I never got around to do the change when I took over maintenance. Feel free to open a PR if you want to.

**Comment by Philippe91** [comment]
SharedDataPtr has better performances than std::shared_ptr because the later uses atomic counters. Atomic counters are not necessary for kiwi and they do have a CPU cost, therefore I would not vote for this change.

**Comment by MatthieuDartiailh** [comment]
Thanks @Philippe91 for catching my shallow knowledge of c++. Would you mind maybe adding a note to this file explaining the interest of using our own implementation, to avoid future issues ?

**Comment by rodrigosetti** [comment]
@Philippe91 I didn't know that. Maybe is worth running the benchmark comparing the two versions? (SharedDataPtr vs std::shared_ptr) (or have you done this test?) Sometimes micro-optimizations like this don't really save CPU cost in practice.

**Comment by Philippe91** [comment]
I have mentioned atomics in my first message. But this is not the sole reason why std::shared_ptr can be expensive.
Another important reason is that std::shared_ptr uses behind the scene a "control block" that requires a separate object allocated on the heap.

Not only a memory allocation is expensive, but that makes the location of the reference counter far away from the counted object itself (hence, not good for CPU cache locality).
SharedData does not have this problem because this is an intrusive counter (SharedData contains the counter and is inherited from).
Now if you know C++ well, you can argue that you could use the special API std::make_shared to avoid this problem.

And BTW, on a minor note, sizeof(SharedDataPtr<T>) is just one pointer large while sizeof(std::shared_ptr<T>) is two pointers large.

Frankly, I don't know what a benchmark would give (and I have not the time to try). Maybe not a big difference.
But in the C++ community, the consensus today is to avoid std::shared_ptr unless there is a good usage reason. Note that I don't say std::shared_ptr is bad; it can be really useful sometimes!
But in the case of kiwi, I don't see the interest in adding overhead just for the sake of using the standard library.

Just google for:
std::shared_ptr cost

and you will see details about my arguments and more.

**Comment by sccolbert** [comment]
The question to ask is “what benefit is there to switching to
std:shared_ptr?” The current code works, and it works with old compilers.
There should be a compelling reason to switch.

**Comment by Qix-** [comment]
-1 on switching. Please check godbolt, on many implementations of libc++, `std::shared_ptr` emits _loads_ of instructions over a simpler implementation. Seconding the remark about atomic counters, too - they are unnecessary here.

**Comment by MatthieuDartiailh** [comment]
Thanks to everybody that shared their expertise on c++. I will close this and merge #108 shortly.
