### ISSUE TITLE
kiwi produces different result compared with another cassowary implementations

### ISSUE THREAD

**Issue by jangko** [nucleic/kiwi#16]
[cassowary-js](http://blog.jramsay.com.au/simplex-solver-using-cassowary-js/) [example](https://gist.github.com/jangko/5f6ee9546c60760b6226) tested with kiwi yields:

```text
Profit: 800
Ale: 12
Beer: 28
Corn: 480
Hops: 160
Malt: 1190   <- ???
```
another cassowary implementations including [python](https://github.com/pybee/cassowary) and [C#](https://github.com/jozilla/Cassowary.net) produce:

```text
Profit: 800
Ale: 12
Beer: 28
Corn: 480
Hops: 160
Malt: 980   <- OK
```

any idea what happened here?

**Comment by sccolbert** [comment]
According to the constraints, Kiwi's solution is still valid. There are multiple valid solutions for `malt` in this example, which means the system is under constrained. There are no guarantees that Kiwi will give the same solution as Cassowary for under constrained systems, since it's not a line-for-line port of Cassowary.
