### ISSUE TITLE
about duplicate constraints

### ISSUE THREAD

**Issue by zsombi** [nucleic/kiwi#160]
Hi,

The following code snippet does not throw DumplicateConstraint:
```
kiwi::Variable v1("var1");
kiwi::Solver solver;

solver.addConstraint(v1 >= 0);
solver.addConstraint(v1 >= 0);
```
From the implementation I can see why it doesn't throw, but I wonder whether should this scenario also be considered as a duplicate constraint?

**Comment by MatthieuDartiailh** [comment]
@sccolbert may have a better intuition on this one...

I will try to look into it though, but feel free to ping if you see by the end of may.

**Comment by sccolbert** [comment]
The solver only tries to protect you from adding the same constraint
*object* more than once, because the internal data pointer they hold needs
to be unique in the system.

It doesn't try to figure out whether two different constraints are the same
equivalent constraint, because that would take a lot of extra processing
for little gain, and it will not affect the solution to the system.

**Comment by MatthieuDartiailh** [comment]
Thanks @sccolbert
