### ISSUE TITLE
Manual solve

### ISSUE THREAD

**Issue by helmesjo** [nucleic/kiwi#26]
This is mostly an optimization issue, but in essence you sometimes know when say 10 variables will be edited at once, and there is no need to solve in between each.

An option to set AutoSolve = true/false would be preferable (like the original implementation), with a dedicated ManualSolve()-method.

**Comment by sccolbert** [comment]
In my testing, I found that that was hardly (never) faster, and was sometimes actually slower than just autosolving all the time. 

My hunch for why this could be is that keeping the system in a solved state requires fewer pivots in total to stay at a correct solution, rather than solving from scratch from a random unsolved state.

**Comment by helmesjo** [comment]
I've only tested this on other implementations, but this might not be the case for your implementation... 

If not, then it's no problem I guess!

**Comment by hfossli** [comment]
Interesting.

**Comment by sccolbert** [comment]
Another benefit of always solving is that you know immediately upon adding a constraint if the system is over-constrained. Without this, it can be difficult to debug the bad constraint if the exception is deferred until everything is added.
