### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by stefanhoelzl** [nucleic/kiwi#58]
Hi,

is there any Documentation/Guide/Reference/HowTo etc. how to use the kiwi python bindings?

Thanks!

**Comment by MatthieuDartiailh** [comment]
As of today not really. I do plan to write docs, but since I am not the original author of the library this takes time.Hopefully they will land at the beginning of 2019.
For basic manipulation of the solver you can have a look at https://github.com/nucleic/kiwi/blob/master/py/tests/test_solver.py. As for a more in depth use, and an example how to use it for GUI layout you can have a look at https://github.com/nucleic/enaml/blob/master/enaml/layout/layout_manager.py and the related files but it may be abrupt.

**Comment by stefanhoelzl** [comment]
Thanks for the links!
Looking forward to see your documentation

**Comment by MatthieuDartiailh** [comment]
The documentation is now online at https://kiwisolver.readthedocs.io/en/latest/
